Repository prgrms-fe-devcourse/FEDC2_TimeDivider_Root, pull requests merged in 2022-06, with the labels that each got.

#7 [컴포넌트] 버튼 컴포넌트 구현
  src/components/Button.jsx
  src/components/Hello.js
  src/stories/Button.stories.jsx
  src/stories/Hello.stories.jsx
Labels: 컴포넌트

#9 [컴포넌트] 공통 컴포넌트 구현
  package-lock.json
  package.json
  src/components/Input.jsx
  src/components/NavBar.jsx
  src/components/Text.jsx
  src/stories/Button.stories.jsx
  src/stories/Input.stories.jsx
  src/stories/NavBar.stories.jsx
  src/stories/Text.stories.jsx
Labels: 컴포넌트

#10 [라우터] 피그마 명세에 따른 페이지 생성 및 라우팅처리
  src/App.js
  src/pages/addToDoTimeDivider.jsx
  src/pages/createTime.jsx
  src/pages/createTimeDivider.jsx
  src/pages/createTodo.jsx
  src/pages/doneToDoTimeDivider.jsx
  src/pages/home.jsx
  src/pages/notFound.jsx
  src/pages/updateTimeDivider.jsx
  src/routes/router.js
  src/routes/routes.js
Labels: 라우터

#12 [컴포넌트] 공통 컴포넌트 수정
  package-lock.json
  src/components/Button.jsx
  src/components/Input.jsx
  src/components/NavBar.jsx
  src/components/Text.jsx
  src/pages/createTime.jsx
  src/stories/Button.stories.jsx
  src/stories/NavBar.stories.jsx
  src/stories/Text.stories.jsx
Labels: 컴포넌트, FIX

#16 [페이지] 모래시계 편집하기 페이지 구현
  package-lock.json
  package.json
  src/App.js
  src/atom.js
  src/pages/updateTimeDivider.jsx
Labels: 페이지, 라이브러리

#17 [페이지] 시간 분배 페이지 구현
  src/components/TaskBox.jsx
  src/components/TaskTimeForm.jsx
  src/pages/createTimeDivider.jsx
Labels: 페이지

#20 fix: TaskBox 클릭 시 다른 박스로 미전환 현상 수정
  src/components/TaskTimeForm.jsx
  src/pages/createTimeDivider.jsx
Labels: FIX

#23 [페이지, UI, FIX] 로그인,회원가입,404페이지 UI 작업 및 #15
  src/components/CardForm.jsx
  src/components/LoginForm.jsx
  src/components/SignUpForm.jsx
  src/hooks/useForm.js
  src/pages/login.jsx
  src/pages/notFound.jsx
  src/pages/signUp.jsx
  src/routes/routes.js
  src/stories/CardForm.stories.jsx
  src/stories/LoginForm.stories.jsx
  src/stories/SignUpForm.stories.jsx
  src/styles/GlobalStyle.js
Labels: 컴포넌트, 스타일, FIX, 페이지

#24 [페이지, 기능구현] 완료하기 클릭시 페이지 구현, 시간 합치기 기능 구현
  package-lock.json
  package.json
  src/App.js
  src/atom.js
  src/components/Timer.jsx
  src/pages/doneToDoTimeDivider.jsx
  src/pages/stateObserver.js
  src/pages/updateTimeDivider.jsx
Labels: 컴포넌트, 페이지

#25 [기능구현, 컴포넌트] Select 컴포넌트 구현 및 각 페이지에 추가
  package-lock.json
  src/components/Select.jsx
  src/components/TaskBox.jsx
  src/components/TimeSelectForm.jsx
  src/pages/createTask.jsx
  src/pages/createTime.jsx
  src/pages/createTimeDivider.jsx
  src/stories/Select.stories.jsx
  src/stories/TimeSelectForm.stories.jsx
  src/utils/convertTime.js
Labels: 컴포넌트, FIX, 페이지

#27 [컴포넌트] 모달 컴포넌트 구현
  src/components/Modal.jsx
  src/hooks/useClickAway.js
  src/stories/Modal.stories.jsx
Labels: 컴포넌트

#28 [기능구현, 페이지, FIX] 추가 클릭시 페이지 구현 및 시간 재생 에러 픽싱
  src/atom.js
  src/components/TimeSelectForm.jsx
  src/components/Timer.jsx
  src/pages/addToDoTimeDivider.jsx
  src/pages/createTimeDivider.jsx
  src/pages/updateTimeDivider.jsx
Labels: FIX, 페이지, 기능구현

#30 [페이지, FIX] 시간 업데이트시 발생하는 버그 수정
  src/pages/createTimeDivider.jsx
Labels: 버그, FIX, 페이지

#33 [리팩터링/컴포넌트/페이지] CreateTimeDivider Page & 관련 컴포넌트 리팩터링
  src/components/Button.jsx
  src/components/Input.jsx
  src/components/Modal.jsx
  src/components/NavBar.jsx
  src/components/Select.jsx
  src/components/TaskBox.jsx
  src/components/TaskTimeForm.jsx
  src/components/TimeSelectForm.jsx
  src/pages/createTimeDivider.jsx
Labels: 컴포넌트, FIX, 페이지, 리팩터링

#34 [리팩토링, 컴포넌트, 페이지] updateTimeDivider Page & 관련 컴포넌트 리팩토링
  src/atom.js
  src/components/FormModal.jsx
  src/components/Modal.jsx
  src/components/Timer.jsx
  src/pages/addToDoTimeDivider.jsx
  src/pages/doneToDoTimeDivider.jsx
  src/pages/updateTimeDivider.jsx
  src/routes/routes.js
Labels: 컴포넌트, 페이지, 리팩터링

#36 [리팩토링] 불필요한 객체 삭제, 컴포넌트 분리, timer 속성 추가 등
  src/atom.js
  src/components/AddFormModal.jsx
  src/components/DoneFormModal.jsx
  src/components/Timer.jsx
  src/pages/createTimeDivider.jsx
  src/pages/updateTimeDivider.jsx
Labels: FIX, 페이지, 리팩터링

#37 [리팩토링] 디렉토리 구조 개선, 절대경로 설정, 담당 페이지 리팩토링
  jsconfig.json
  src/App.js
  src/pages/createTask.jsx
  src/pages/createTime.jsx
  src/pages/createTimeDivider.jsx
  src/pages/home.jsx
  src/pages/login.jsx
  src/pages/notFound.jsx
  src/pages/signUp.jsx
  src/pages/stateObserver.js
  src/pages/updateTimeDivider.jsx
  src/shared/components/AddFormModal.jsx
  src/shared/components/Button.jsx
  src/shared/components/CardForm.jsx
  src/shared/components/DoneFormModal.jsx
  src/shared/components/FormModal.jsx
  src/shared/components/Input.jsx
  src/shared/components/LoginForm.jsx
  src/shared/components/Modal.jsx
  src/shared/components/NavBar.jsx
  src/shared/components/Select.jsx
  src/shared/components/SignUpForm.jsx
  src/shared/components/TaskBox.jsx
  src/shared/components/TaskTimeForm.jsx
  src/shared/components/Text.jsx
  src/shared/components/TimeSelectForm.jsx
  src/shared/components/Timer.jsx
  src/shared/constants/colors.js
  src/shared/hooks/useClickAway.js
  src/shared/hooks/useForm.js
  src/shared/utils/convertTime.js
Labels: 리팩터링

#41 [스타일] container 크기 수정 및 마이너 수정
  src/shared/constants/colors.js
  src/styles/GlobalStyle.js
Labels: 스타일, FIX

#42 [스타일] 컬러 변수 세부 수정
  src/pages/home.jsx
  src/pages/updateTimeDivider.jsx
  src/shared/components/Button.jsx
  src/shared/components/Timer.jsx
  src/shared/constants/colors.js
  src/styles/GlobalStyle.js
Labels: 스타일

#44 [컴포넌트] Button 컴포넌트 수정 및 각 페이지 반영
  src/pages/createTask.jsx
  src/pages/createTime.jsx
  src/pages/createTimeDivider.jsx
  src/pages/home.jsx
  src/pages/notFound.jsx
  src/pages/updateTimeDivider.jsx
  src/shared/components/Button.jsx
  src/shared/components/TimeSelectForm.jsx
  src/stories/Button.stories.jsx
Labels: 컴포넌트, FIX

#45 [스타일, 리팩토링, FIX, 컴포넌트, 페이지]
  src/atom.js
  src/pages/updateTimeDivider.jsx
  src/shared/components/AddFormModal.jsx
  src/shared/components/DoneFormModal.jsx
  src/shared/components/FormModal.jsx
  src/shared/components/MergeFormModal.jsx
  src/shared/components/Modal.jsx
  src/shared/components/Timer.jsx
Labels: 컴포넌트, 스타일, FIX, 페이지, 리팩터링

#46 [컴포넌트] Select 컴포넌트 디자인 수정
  .storybook/preview.js
  src/shared/components/Select.jsx
  src/stories/Select.stories.jsx
Labels: 컴포넌트, FIX

#48 [스타일] navBar 스타일링 완료
  src/shared/components/NavBar.jsx
Labels: 컴포넌트, 스타일

#49 [스타일] 홈-오늘의시간-오늘의할일 페이지 스타일링 완료, input 컴포넌트 수정
  src/pages/createTask.jsx
  src/pages/createTime.jsx
  src/pages/home.jsx
  src/shared/components/Button.jsx
  src/shared/components/Input.jsx
  src/shared/components/Select.jsx
  src/shared/constants/colors.js
  src/stories/Button.stories.jsx
  src/styles/GlobalStyle.js
Labels: 컴포넌트, 스타일, 페이지

#51 [컴포넌트] navbar gobackicon 클릭 시 뒤로가기 구현
  src/shared/components/NavBar.jsx
Labels: 컴포넌트, 기능구현

#53 [스타일] 뷰포트 크기에 따른 height 크기를 지정
  src/pages/createTask.jsx
  src/pages/createTime.jsx
  src/styles/GlobalStyle.js
Labels: 스타일

#55 [환경설정] axios 인스턴스 설정
  src/pages/signUp.jsx
  src/shared/api/API.jsx
  src/shared/api/apis/authApis.js
  src/shared/api/apis/userApis.js
  src/shared/api/index.jsx
  src/shared/components/SignUpForm.jsx
  src/shared/hooks/useForm.js
Labels: 환경설정

#60 [리팩터링] 오늘의시간, 할일적기 페이지 리팩터링
  src/App.js
  src/pages/createTask.jsx
  src/pages/createTime.jsx
  src/pages/createTimeDivider.jsx
  src/shared/components/Text.jsx
  src/shared/hooks/useCreateTasks.js
  src/shared/hooks/useNavigation.js
Labels: 리팩터링

#61 [컴포넌트] Badge 컴포넌트 추가
  src/pages/createTask.jsx
  src/shared/components/Badge.jsx
  src/shared/constants/colors.js
  src/stories/Badge.stories.jsx
Labels: 컴포넌트

#64 [리팩토링] page 디렉토리 관리
  src/pages/CreateTask/index.js
  src/pages/CreateTask/style.js
  src/pages/CreateTime/index.js
  src/pages/CreateTime/style.js
  src/pages/CreateTimeDivider/index.js
  src/pages/CreateTimeDivider/style.js
  src/pages/Home/index.js
  src/pages/Home/style.js
  src/pages/Login/index.js
  src/pages/MyPage/index.js
  src/pages/NotFound/index.js
  src/pages/NotFound/style.js
  src/pages/ShareTask/index.js
  src/pages/SignUp/index.js
  src/pages/UpdateTimeDivider/index.js
  src/pages/home.jsx
Labels: 리팩터링

#66 [리팩토링] src 내부 디렉토리 관리
  src/App.js
  src/pages/CreateTask/index.js
  src/pages/CreateTimeDivider/index.js
  src/pages/Home/index.js
  src/pages/createTask.jsx
  src/pages/router.js
  src/pages/routes.js
  src/shared/images/logoTimeDivider.png
Labels: 리팩터링

#68 [컴포넌트] Avatar, TaskCard 컴포넌트 구현
  README.md
  src/pages/CreateTask/index.js
  src/pages/ShareTask/index.js
  src/shared/components/Avatar.jsx
  src/shared/components/Badge.jsx
  src/shared/components/TaskCard.jsx
  src/shared/hooks/useToggle.js
  src/stories/Avatar.stories.jsx
  src/stories/TaskCard.stories.jsx
Labels: 컴포넌트

#71 [페이지, 컴포넌트] 마이페이지 구현
  src/pages/MyPage/index.js
  src/pages/MyPage/style.js
  src/shared/components/ToggleButton.jsx
Labels: 컴포넌트, 페이지

#74 [FIX/컴포넌트] Avatar 사이즈 적용 버그 수정
  src/pages/ShareTask/index.js
  src/shared/components/Avatar.jsx
  src/shared/components/TaskCard.jsx
  src/stories/Avatar.stories.jsx
Labels: 컴포넌트, FIX

#73 [페이지] 회원가입, 로그인 API 연결 및 로그인정보 sessionStorage 저장
  src/pages/CreateTimeDivider/index.js
  src/pages/Login/components/LoginForm.jsx
  src/pages/Login/index.js
  src/pages/SignUp/components/SignUpForm.jsx
  src/pages/SignUp/index.js
  src/pages/UpdateTimeDivider/index.js
  src/pages/routes.js
  src/shared/api/apis/authApis.js
  src/shared/components/AddFormModal.jsx
  src/shared/components/CardForm.jsx
  src/shared/components/DoneFormModal.jsx
  src/shared/components/LoginForm.jsx
  src/shared/components/MergeFormModal.jsx
  src/shared/components/SignUpForm.jsx
  src/shared/components/Timer.jsx
  src/shared/hooks/useForm.js
  src/state/timer.js
  src/state/user.js
  src/state/utils/storage.js
  src/stories/LoginForm.stories.jsx
  src/stories/SignUpForm.stories.jsx
Labels: 기능구현

#75 [컴포넌트, 페이지] 하단 바 컴포넌트 구현 및 페이지 별 적용
  src/pages/MyPage/index.js
  src/pages/MyPage/style.js
  src/pages/ShareTask/index.js
  src/pages/UpdateTimeDivider/index.js
  src/pages/UpdateTimeDivider/style.js
  src/shared/components/BottomBar.jsx
  src/shared/images/board.png
  src/shared/images/clock.png
  src/shared/images/profile.png
Labels: 컴포넌트, 페이지

#76 [기능] 로그인 성공시 axios instance에 token 세팅
  src/shared/api/API.js
  src/shared/api/apis/authApis.js
Labels: 기능구현

#77 [리팩토링] useTimers 커스텀 훅 구현, event handler 리팩토링
  src/pages/UpdateTimeDivider/components/AddFormModal.jsx
  src/pages/UpdateTimeDivider/components/CompleteFormModal.jsx
  src/pages/UpdateTimeDivider/components/MergeFormModal.jsx
  src/pages/UpdateTimeDivider/components/ToolBarButton.jsx
  src/pages/UpdateTimeDivider/index.js
  src/shared/components/DoneFormModal.jsx
  src/shared/components/Timer.jsx
  src/shared/hooks/useTimers.js
Labels: 컴포넌트, 리팩터링

#80 [페이지] Share Task 페이지 UI 구현
  src/pages/Login/components/LoginForm.jsx
  src/pages/ShareTask/index.js
  src/shared/components/Badge.jsx
  src/shared/components/TaskCard.jsx
  src/shared/constants/colors.js
Labels: 페이지

#84 [라우터] 로그인화면 플로우 관련 라우팅 페이지 추가
  src/pages/CreateTask/hooks/useCreateTasks.js
  src/pages/CreateTask/index.js
  src/pages/MyPageLogin/index.js
  src/pages/SelectUserType/index.js
  src/pages/routes.js
Labels: 라우터

#85 [페이지] 로그아웃, 편집하기 레이아웃 추가
  README.md
  package-lock.json
  package.json
  src/pages/MyPage/index.js
  src/pages/MyPage/style.js
  src/pages/MyPageLogin/index.js
  src/pages/routes.js
  src/shared/constants/colors.js
Labels: 페이지

#86 [페이지, 라우팅, Axios] flow2에 맞춰서 라우팅 처리 수정, Axios 인터셉터 추가
  src/pages/Login/index.js
  src/pages/MyPageLogin/index.js
  src/pages/NotFound/index.js
  src/pages/SelectUserType/components/SelectUserTypeForm.jsx
  src/pages/SelectUserType/index.js
  src/pages/SignUp/components/SignUpForm.jsx
  src/pages/SignUp/index.js
  src/pages/routes.js
  src/shared/api/API.js
  src/shared/api/apis/authApis.js
Labels: 라우터, 환경설정, 기능구현, 리팩터링

#87 [페이지] 마이페이지 편집 화면 구현 및 useUser Hooks 추가
  src/pages/MyPage/index.js
  src/pages/MyPageEdit/index.js
  src/pages/routes.js
  src/shared/hooks/useUser.js
Labels: 페이지

#88 [페이지] 로그아웃 기능 구현
  src/pages/MyPage/index.js
  src/pages/MyPage/style.js
  src/shared/api/apis/authApis.js
  src/shared/hooks/useUser.js
Labels: 페이지

#90 [페이지/기능구현] 포스트 좋아요 및 댓글 기능 구현
  src/pages/ShareTask/index.js
  src/shared/api/apis/commentApis.js
  src/shared/api/apis/likeApis.js
  src/shared/api/index.js
  src/shared/components/Comment.jsx
  src/shared/components/TaskCard.jsx
  src/shared/utils/storage.js
Labels: 컴포넌트, 페이지, 기능구현

#93 [FIX, 리팩토링] 오늘의시간, 오늘의 할일 페이지 전역 상태관리로 수정
  src/pages/CreateSpareTime/components/TimeSelecForm.jsx
  src/pages/CreateSpareTime/index.js
  src/pages/CreateSpareTime/style.js
  src/pages/CreateTask/hooks/useCreateTasks.js
  src/pages/CreateTask/index.js
  src/pages/CreateTime/index.js
  src/pages/CreateTimeDivider/index.js
  src/pages/CreateTimerName/hooks/useNameTag.js
  src/pages/CreateTimerName/index.js
  src/pages/CreateTimerName/style.js
  src/pages/Home/index.js
  src/pages/routes.js
  src/shared/components/SubTitle.jsx
  src/shared/components/TaskBox.jsx
  src/shared/hooks/useCreatingTimers.js
  src/state/creatingTimer.js
Labels: FIX, 리팩터링

#94 [FIX, 기능구현] 타이머 초기화, 로그인 및 회원가입 성공 경로 수정
  src/pages/Login/index.js
  src/pages/SignUp/index.js
  src/shared/hooks/useTimers.js
  src/shared/hooks/useUser.js
Labels: FIX, 기능구현

#95 [기능구현, 페이지] 편집 페이지 기능 구현, 더미 이미지 삽입 구현
  src/pages/Login/index.js
  src/pages/MyPage/index.js
  src/pages/MyPageEdit/index.js
  src/pages/MyPageEdit/style.js
  src/shared/api/apis/userApis.js
  src/shared/hooks/useUser.js
  src/shared/images/dummyUser.png
  src/state/user.js
Labels: 페이지, 기능구현

#96 [페이지] 할 일 공유 페이지 구현
  src/pages/DeatailPost/index.js
  src/pages/DeatailPost/style.js
  src/pages/ShareTask/components/AvatarItem.jsx
  src/pages/ShareTask/index.js
  src/pages/ShareTask/style.js
  src/pages/routes.js
  src/shared/api/API.js
  src/shared/api/apis/postApis.js
  src/shared/components/CommentForm.jsx
  src/shared/components/CommentList.jsx
  src/shared/components/PostCard.jsx
  src/shared/components/TaskCard.jsx
Labels: 라우터, 페이지, 기능구현

#97 [페이지] 로그인, 회원가입 페이지 퍼블리싱 및 리팩토링
  .eslintrc.json
  src/pages/Login/components/Divider.jsx
  src/pages/Login/components/LoginForm.jsx
  src/pages/Login/index.js
  src/pages/Login/style.js
  src/pages/SelectUserType/components/SelectUserTypeForm.jsx
  src/pages/SelectUserType/index.js
  src/pages/SignUp/components/SignUpForm.jsx
  src/pages/SignUp/index.js
  src/pages/routes.js
  src/shared/api/apis/authApis.js
  src/shared/api/apis/postApis.js
  src/shared/components/CardForm.jsx
  src/shared/components/Logo.jsx
  src/shared/hooks/useUser.js
Labels: 스타일, 리팩터링

#98 [디자인] 반응형 레이아웃 구현
  public/index.html
  src/styles/GlobalStyle.js
Labels: 스타일

#99 [페이지] 포스트 상세보기 페이지 구현
  src/pages/DeatailPost/index.js
  src/pages/DetailPost/index.js
  src/pages/DetailPost/style.js
  src/pages/ShareTask/components/AvatarItem.jsx
  src/pages/ShareTask/index.js
  src/pages/routes.js
  src/shared/api/apis/postApis.js
  src/shared/components/CommentList.jsx
  src/shared/components/PostCard.jsx
Labels: 라우터, 페이지, 기능구현

#103 [스타일] shareTask, detailPost 페이지 스타일링, 로딩 이미지 추가
  src/pages/DetailPost/index.js
  src/pages/DetailPost/style.js
  src/pages/Login/index.js
  src/pages/MyPage/index.js
  src/pages/MyPageEdit/index.js
  src/pages/ShareTask/components/AvatarItem.jsx
  src/pages/ShareTask/index.js
  src/pages/ShareTask/style.js
  src/shared/components/Button.jsx
  src/shared/components/CommentForm.jsx
  src/shared/components/CommentList.jsx
  src/shared/components/PostCard.jsx
  src/shared/hooks/usePosts.js
  src/shared/images/loading.gif
Labels: 스타일

#104 [README] README.md 수정
  README.md
  src/README.md
Labels: 문서

#105 [문서] 리드미 수정
  README.md
Labels: 문서
